#!/bin/bash

IN_FILE="${1}"
OUT_FILE="${1}.sed"

ACTIVITY_ID_PROFESSIONAL_SERVICES=10
ACTIVITY_ID_TRACKING_ACTIVITY=17
ACTIVITY_ID_IT_TICKET_TRACKING=49
ACTIVITY_ID_DEVELOPMENT=13
ACTIVITY_ID_DEV_OPS=280
ACTIVITY_ID_PM=281
ACTIVITY_ID_CRITICAL_ISSUE=282
ACTIVITY_ID_AFTERHOURS_SUPPORT=283

JIR_PREFIX=${2}
TASK_ID=${3}
ACTIVITY_ID=${4}
DATE=${5}

cat "${IN_FILE}" | tr '\n' '\r' | sed -e "s/\(Task\|Story\|Bug\)\{0,1\}\([^\r]*\)\r\(${JIR_PREFIX}-[0-9]\+\)\r[0-9 mh]\+\r\([0-9.]\+\)\r\{0,1\}/${TASK_ID}, ${ACTIVITY_ID}, \4, \3 - \2, ${DATE}\n/g" | tr '\r' '\n' > "${OUT_FILE}"

mv "${OUT_FILE}" "${IN_FILE}"
