#!/usr/bin/env bash

# for zsh startup files order see:
# http://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source ./link${COLOR_NC}"
else

  SOURCE=${BASH_SOURCE[0]}
  if [ -z $SOURCE ]; then
    SOURCE=$0
  fi
  BASEDIR=$(cd "$(dirname "$SOURCE")"; pwd)
  echo "BASEDIR: $BASEDIR"

  link () {
    echo -e "\nDo link\n$1\n$2\n"
    ls -l $2
    echo

    if [ -L $2 ]; then
      DSTLINK=$(readlink $2)
      if [ "$DSTLINK" = "$1" ]; then
        echo -e "Link already done!\n"
        return
      fi
    fi

    if [ -e $1 ]; then
      if [ -d $2 ]; then        
        rm -i -r $2
      fi
      if [ -e $2 ]; then
        rm -i $2
      fi
      if [ -L $2 ]; then
        rm -i $2
      fi

      if [ -e $2 ]; then
        echo -e "\nDestination was not removed!"
      else
        ln -s $1 $2
      fi
    else
      echo -e "Source does not exist!"
    fi

    echo
  }

  # bash
  link $BASEDIR/bash_profile $HOME/.bash_profile
  link $BASEDIR/bashrc $HOME/.bashrc
  link $BASEDIR/profile $HOME/.profile
  link $BASEDIR/bash_logout $HOME/.bash_logout

  # zsh
  link $BASEDIR/zshenv $HOME/.zshenv
  link $BASEDIR/zprofile $HOME/.zprofile
  link $BASEDIR/zshprompt $HOME/.zshprompt
  link $BASEDIR/zshrc $HOME/.zshrc

  # Oh My Zsh custom plugins are loaded via ZSH_CUSTOM in zshrc (this folder in
  # git). Do not symlink over ~/.oh-my-zsh/custom: omz update cannot autostash
  # tracked example files that sit behind a symlink.
  OMZ_CUSTOM="$HOME/.oh-my-zsh/custom"
  SETTINGS_CUSTOM="$BASEDIR/oh-my-zsh/custom"
  if [ -d "$HOME/.oh-my-zsh" ]; then
    if [ -L "$OMZ_CUSTOM" ]; then
      DSTLINK=$(readlink "$OMZ_CUSTOM")
      if [ "$DSTLINK" = "$SETTINGS_CUSTOM" ]; then
        echo "Migrate OMZ custom: drop settings symlink, restore OMZ's own custom/"
        echo "Plugins load from ZSH_CUSTOM: $SETTINGS_CUSTOM"
        rm "$OMZ_CUSTOM"
        if [ -e "$OMZ_CUSTOM" ]; then
          echo "OMZ custom was not removed; skip restore"
        else
          git -C "$HOME/.oh-my-zsh" checkout -- custom/
          if [ ! -d "$OMZ_CUSTOM" ]; then
            echo "OMZ custom restore failed; creating empty directory"
            mkdir -p "$OMZ_CUSTOM"
          fi
        fi
      else
        echo "Skip OMZ custom migrate: $OMZ_CUSTOM points to $DSTLINK"
      fi
    fi
  else
    echo "Skip OMZ custom migrate: $HOME/.oh-my-zsh is missing (install Oh My Zsh first)"
  fi
  unset OMZ_CUSTOM SETTINGS_CUSTOM DSTLINK

  # vim
  link $BASEDIR/vim/vimrc $HOME/.vimrc
  link $BASEDIR/vim/gvimrc $HOME/.gvimrc
  link $BASEDIR/vim $HOME/.vim

  # git
  link $BASEDIR/gitconfig $HOME/.gitconfig
  link $BASEDIR/gitattributes $HOME/.gitattributes
  link $BASEDIR/gitk $HOME/.gitk
  link $BASEDIR/git-prompt.sh $HOME/.git-prompt.sh

  # config
  link $BASEDIR/config/glogg $HOME/.config/glogg
  link $BASEDIR/config/htop $HOME/.config/htop
  link $BASEDIR/config/mc $HOME/.config/mc
  link $BASEDIR/config/ghostty $HOME/.config/ghostty

  # tmux
  link $BASEDIR/tmux $HOME/.tmux
  link $BASEDIR/tmux.conf $HOME/.tmux.conf

  # misc
  link $BASEDIR/aliases $HOME/.aliases
  link $BASEDIR/inputrc $HOME/.inputrc
  link $BASEDIR/toprc $HOME/.toprc
  link $BASEDIR/shell_set_colors $HOME/.shell_set_colors
  link $BASEDIR/ls_dir_set_colors $HOME/.ls_dir_set_colors

fi
