#echo -e "\n\nExecuting ~/.zshenv\n\n"

###########################################################
# Export vars

export LOCAL_LIB=$HOME/lib

#export LOCAL_JAVA_HOME_32=$LOCAL_LIB/java/jre1.6.0_34
#export LOCAL_JAVA_HOME_64=$LOCAL_LIB/java/jre1.6.0_34_x64

#export JAVA_HOME=$SYS_JAVA_HOME

export MAVEN_OPTS="-Xmx4192m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd'T'HH:mm:ss.SSSZ -Duser.timezone=UTC -Djava.net.preferIPv4Stack=true"
export MAVEN_HOME=$LOCAL_LIB/maven

export PATH=$PATH:$MAVEN_HOME/bin

# Add custom scripts to ~/bin
export PATH=$PATH:$HOME/bin

# Add one binary programs to ~/lib/bin
export PATH=$PATH:$HOME/lib/bin

export PATH=$PATH:$HOME/lib/jmeter/bin

# Add pip local bin (prepended so user-installed binaries shadow system ones)
export PATH=$HOME/.local/bin:$PATH

# Add go bin
export PATH=$PATH:$HOME/go/bin

# Add tfenv check https://github.com/tfutils/tfenv
export PATH=$PATH:$HOME/.tfenv/bin

# Add cargo bin
export PATH=$PATH:$HOME/.cargo/bin

# Perforce custom envs
export P4CONFIG=.p4config
export P4EDITOR=vim
export P4MERGE=kdiff3

export PYTHONPATH=$PYTHONPATH:~/lib/pywikipedia/

export GTEST_DIR=$HOME/develop/private/gtest/gtest-1.6.0

export RSYNC_PARTIAL_DIR=$HOME/.rsync-tmp

export HELM_HOME=$HOME/.helm

# Do not use source instead of . in env files
# it does not work for desktop managers env load

[ -s ~/.awsenv ] && . ~/.awsenv

######################################################################
# nvm

export NVM_DIR="$HOME/.nvm"

[ -s "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

######################################################################
# bun

export BUN_INSTALL="$HOME/.bun"

export PATH="$BUN_INSTALL/bin:$PATH"

######################################################################
# !!! KEEP THIS AT THE END OF .zshenv

# Add local PC shell settings
# Disable this if you use rsync and ssh or scp
[ -s ~/.localenv ] && . ~/.localenv
